pub const PLAYER_SPEED: f32 = 300.0;
pub const PLAYER_SCALE: f32 = 4.0;
pub const PLAYER_INITIAL_HEALTH: i32 = 100;
pub const PLAYER_HEALTH_BAR_WIDTH: f32 = 220.0;
pub const PLAYER_HEALTH_BAR_HEIGHT: f32 = 22.0;
pub const PLAYER_HEALTH_BAR_MARGIN: f32 = 18.0;
pub const PLAYER_DEATH_DISPLAY_SECONDS: f32 = 2.5;
pub const PLAYER_DEATH_MESSAGE: &str = "YOU DIED";
pub const PLAYER_DEATH_FONT_PATH: &str = "fonts/NotoSans-Regular.ttf";
pub const PLAYER_DEATH_FONT_SIZE: f32 = 96.0;
pub const PLAYER_DEATH_TEXT_COLOR: [f32; 4] = [0.86, 0.2, 0.18, 1.0];
pub const PLAYER_DEATH_OVERLAY_COLOR: [f32; 4] = [0.0, 0.0, 0.0, 0.65];

pub const PLAYER_STATS_FONT_PATH: &str = "fonts/NotoSans-Regular.ttf";
pub const PLAYER_STATS_FONT_SIZE: f32 = 20.0;
pub const PLAYER_STATS_PANEL_WIDTH: f32 = 360.0;
pub const PLAYER_STATS_PANEL_HEIGHT: f32 = 110.0;
pub const PLAYER_STATS_PANEL_TOP_OFFSET: f32 =
    PLAYER_HEALTH_BAR_MARGIN + PLAYER_HEALTH_BAR_HEIGHT + 12.0;
pub const PLAYER_STATS_PANEL_LEFT_OFFSET: f32 = PLAYER_HEALTH_BAR_MARGIN;

pub const WEAPON_SCALE: f32 = 1.0;
pub const PLAYER_BASE_ATTACK: i32 = 15;
pub const PLAYER_BASE_DEFENSE: i32 = 4;
pub const PLAYER_ATTACK_RADIUS: f32 = 48.0;
pub const PLAYER_ATTACK_REACH: f32 = 24.0;
pub const PLAYER_ATTACK_FACING_COS_THRESHOLD: f32 = 0.25;

pub const DOOR_INTERACTION_RADIUS: f32 = ROOM_TILE_SIZE * PLAYER_SCALE * 1.5;
pub const DOOR_INTERACTION_FACING_COS_THRESHOLD: f32 = 0.5;

pub const CAMERA_FOLLOW_SPEED: f32 = 3.0;

pub const GRID_SIZE: usize = 20;
pub const TILE_SIZE: f32 = 32.0;

pub const ROOM_TILE_SIZE: f32 = 16.0;
pub const Z_LAYER_GRID: f32 = 0.0;

pub const INPUT_DEADZONE: f32 = 0.1;

pub const SLIME_SCALE: f32 = 4.0;
pub const SLIME_HEALTH: i32 = 35;
pub const SLIME_PATROL_RANGE: f32 = 120.0;
pub const SLIME_PATROL_SPEED: f32 = 60.0;
pub const SLIME_CHASE_SPEED: f32 = 90.0;
pub const SLIME_ALERT_RADIUS: f32 = 200.0;
pub const SLIME_LEASH_RADIUS: f32 = 260.0;
pub const SLIME_BASE_ATTACK: i32 = 5;
pub const SLIME_BASE_DEFENSE: i32 = 2;
pub const SLIME_ATTACK_RADIUS: f32 = 28.0;
pub const SLIME_ATTACK_COOLDOWN: f32 = 1.0;

pub const CYCLOPS_SCALE: f32 = 4.5;
pub const CYCLOPS_HEALTH: i32 = 80;
pub const CYCLOPS_PATROL_RANGE: f32 = 140.0;
pub const CYCLOPS_PATROL_SPEED: f32 = 55.0;
pub const CYCLOPS_CHASE_SPEED: f32 = 85.0;
pub const CYCLOPS_ALERT_RADIUS: f32 = 220.0;
pub const CYCLOPS_LEASH_RADIUS: f32 = 220.0;
pub const CYCLOPS_BASE_ATTACK: i32 = 12;
pub const CYCLOPS_BASE_DEFENSE: i32 = 6;
pub const CYCLOPS_WINDUP_SECONDS: f32 = 0.6;
pub const CYCLOPS_CHARGE_SECONDS: f32 = 0.45;
pub const CYCLOPS_CHARGE_MULTIPLIER: f32 = 2.2;
pub const CYCLOPS_COOLDOWN_SECONDS: f32 = 1.2;

pub const ENEMY_HEALTH_BAR_WIDTH: f32 = 50.0;
pub const ENEMY_HEALTH_BAR_HEIGHT: f32 = 6.0;
pub const ENEMY_HEALTH_BAR_OFFSET_Y: f32 = 48.0;

pub const PLAYER_DAMAGE_FLASH_COUNT: u8 = 4;
pub const PLAYER_DAMAGE_FLASH_INTERVAL: f32 = 0.08;
pub const PLAYER_DAMAGE_FLASH_COLOR: [f32; 4] = [1.0, 0.4, 0.4, 1.0];

pub const ENEMY_DEATH_FADE_SECONDS: f32 = 0.45;
